sudo: required ## 관리자 권한갖기

language: generic ## 언어 플랫폼을 선택

services: ## 도커 환경 구성
  - docker

before_install: ## 스크립트를 실행할 수 있게 빌드 
  - echo "start createing an image with dockerfile"
  - docker build -t fada2020/react-app -f Dockerfile.dev .

script: ## 실행할 스크립트
  - docker run -e CI=true fada2020/react-app npm run test -- --coverage

after_success: ## 테스트 성공 후에 ㅏㄹ일
  - echo "Test success"